on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Create blank versions of configured file
        run: echo -e "" >> src/config.rs
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  flatpak:
    name: Flatpak
    runs-on: ubuntu-24.04
    container:
      image: flatpak/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: based.flatpak
        manifest-path: build-aux/com.kylobytes.Based.Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }}
